### ISSUE TITLE
AttributeError: 'DXCamera' object has no attribute 'is_capturing'

### ISSUE THREAD

**Issue by XJY00** [solarorb93/MMCensor#14]
```
E:\MMCensor-0.41f>call ./winpython-pytorch-cpu/WPy64-31241/scripts/env_for_icons.bat
starting
Traceback (most recent call last):
  File "E:\MMCensor-0.41f\mmc_code\mmcensor_realtime.py", line 6, in <module>
    s.initialize()
  File "E:\MMCensor-0.41f\mmc_code\mmcensor\gui\gui.py", line 44, in initialize
    self.rt.initialize()
  File "E:\MMCensor-0.41f\mmc_code\mmcensor\rt\rt.py", line 406, in initialize
    self.sc.initialize()
  File "E:\MMCensor-0.41f\mmc_code\mmcensor\rt\rt.py", line 41, in initialize
    self.populate_dxcams()
  File "E:\MMCensor-0.41f\mmc_code\mmcensor\rt\rt.py", line 63, in populate_dxcams
    self.cams = get_dxcams()
                ^^^^^^^^^^^^
  File "E:\MMCensor-0.41f\mmc_code\mmcensor\rt\rt.py", line 32, in get_dxcams
    cam = dxcam.create( device_idx=i, output_idx=j, output_color='BGR' )
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\MMCensor-0.41f\winpython-pytorch-cpu\WPy64-31241\python-3.12.4.amd64\Lib\site-packages\dxcam\__init__.py", line 112, in create
    return __factory.create(
           ^^^^^^^^^^^^^^^^^
  File "E:\MMCensor-0.41f\winpython-pytorch-cpu\WPy64-31241\python-3.12.4.amd64\Lib\site-packages\dxcam\__init__.py", line 71, in create
    camera = DXCamera(
             ^^^^^^^^^
  File "E:\MMCensor-0.41f\winpython-pytorch-cpu\WPy64-31241\python-3.12.4.amd64\Lib\site-packages\dxcam\dxcam.py", line 33, in __init__
    self._duplicator: Duplicator = Duplicator(
                                   ^^^^^^^^^^^
  File "<string>", line 6, in __init__
  File "E:\MMCensor-0.41f\winpython-pytorch-cpu\WPy64-31241\python-3.12.4.amd64\Lib\site-packages\dxcam\core\duplicator.py", line 19, in __post_init__
    output.output.DuplicateOutput(device.device, ctypes.byref(self.duplicator))
_ctypes.COMError: (-2005270524, '指定的设备接口或功能级别在此系统上不受支持。', (None, None, None, 0, None))
Exception ignored in: <function DXCamera.__del__ at 0x000002283AD0A8E0>
Traceback (most recent call last):
  File "E:\MMCensor-0.41f\winpython-pytorch-cpu\WPy64-31241\python-3.12.4.amd64\Lib\site-packages\dxcam\dxcam.py", line 243, in __del__
    self.release()
  File "E:\MMCensor-0.41f\winpython-pytorch-cpu\WPy64-31241\python-3.12.4.amd64\Lib\site-packages\dxcam\dxcam.py", line 238, in release
    self.stop()
  File "E:\MMCensor-0.41f\winpython-pytorch-cpu\WPy64-31241\python-3.12.4.amd64\Lib\site-packages\dxcam\dxcam.py", line 138, in stop
    if self.is_capturing:
       ^^^^^^^^^^^^^^^^^
AttributeError: 'DXCamera' object has no attribute 'is_capturing'
请按任意键继续. . .
```

**Comment by shijiu101** [comment]
我这里也遇到了相同的问题，有没有解决方案
